### ISSUE TITLE
Missing method Docslice?

### ISSUE THREAD

**Issue by OkkeKlein** [SeaseLtd/composite-request-handler#1]
Caused by: org.apache.solr.common.SolrException: org.apache.solr.search.DocSlice.<init>(II[I[FJF)V
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:977)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:830)
	at org.apache.solr.core.CoreContainer.createFromDescriptor(CoreContainer.java:950)
	... 7 more
Caused by: java.lang.NoSuchMethodError: org.apache.solr.search.DocSlice.<init>(II[I[FJF)V
	at io.sease.crh.CompositeRequestHandler.<clinit>(CompositeRequestHandler.java:68)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:539)
	at org.apache.solr.core.SolrResourceLoader.findClass(SolrResourceLoader.java:486)
	at org.apache.solr.core.SolrCore.createInstance(SolrCore.java:753)
	at org.apache.solr.core.PluginBag.createPlugin(PluginBag.java:133)
	at org.apache.solr.core.PluginBag.init(PluginBag.java:269)
	at org.apache.solr.core.RequestHandlers.initHandlersFromConfig(RequestHandlers.java:130)
	at org.apache.solr.core.SolrCore.<init>(SolrCore.java:935)
	... 9 more

**Comment by agazzarini** [comment]
Hi @OkkeKlein I just 

- cloned the repository   
- changed the solr.version in pom.xml   
- mvn clean install   

and everything is working. Could you please expand a bit about how you're using this handler?    

My shoot in the dark is one of the following:    

- you followed the README using the version 1.0 (which has been compiled using Solr 7.1.0) on a Solr 6.6.6. At first thought I'm not sure why it shouldn't work     
- you cloned and built the repository without changing the solr.version in the pom.xml   
   
Let me know, I'm happy to help.

**Comment by OkkeKlein** [comment]
OK. It seems to work now. At least when I put it in solrconfig.xml. 

if I try to include it from another file it goes wrong:

<xi:include href="solrconfig_autocomplete.xml" xmlns:xi="http://www.w3.org/2001/XInclude">
    <xi:fallback></xi:fallback>
</xi:include>

Thank you and feel free to close the issue.

**Comment by OkkeKlein** [comment]
Back on this issue. I am trying to create a jar for Solr 8.7.0. But on mvn install I get

[ERROR] /E:/Workspace/files/Java/composite-request-handler-master/src/main/java/io/sease/crh/CompositeRequestHandler.java:[67,54] constructor DocSlice in class org.apache.solr.search.DocSlice cannot be applied to given types;
  required: int,int,int[],float[],long,float,org.apache.lucene.search.TotalHits.Relation
  found: int,int,int[],float[],int,float
  reason: actual and formal argument lists differ in length

Thanks for any help you can provide.
